version: 0.2.{build}
init:
- cinst autoit.commandline
build: off
test_script:
- git submodule update --init --recursive
- cd testing
- autoit3 /ErrorStdOut /AutoIt3ExecuteScript test-drive-mapper.au3 ci